## List of all files used as input

Design:
  [LibASeqDesign] 
# All options: LibASeqDesign, LibHSeqDesign, LibBSeqDesign

FastqDir:
  [LibraryA_minPInitial] 
# All options: LibraryA_minPInitial, LibraryA_minPOptimized, LibraryH_minP, LibraryH_minCMV, LibraryB_minP

LibraryName:
  [LibAminPInitial] 
# All options: LibAminPInitial, LibAminPOpt, LibraryH_minP, LibBminP

threads_bwa: 8

# here enter path to directory with fastq files
InDir: "/path/to/crs-bc-fastq/folder" 

# output directory of the CRS-BC association
OutDir: "path/to/project/folder/Pipelines/MPRA/1_CRS_BC_association/output_snake" 

#  Which design folders to use
DesignFolder: "path/to/design/folder" 
